function impressCrush() {
    var pickupLines = [
        "Are you a ghost train? Because i am going to scream when i ride you.",
        "Are you a book? Because i wanna take page number 69 without your permission.",
        "Are you a gym trainer? Because i have one muscle that needs a lot of work.",
        "Are you a school? Because i wanna put my kids in you.",
        "If your right leg is christmas and your left leg is new year? Can i visit between the holidays?",
        "May i be the first one to open the door which can't be closed again!",
        "Kiss me if I am wrong but dinosaurs still exist,right?",
        "Do you think karma is not real? I know some karma-sutra that might change your mind.",
        "Are you an umbrella.? I urgently need to be under you.",
        "Your legs may be tired,you can keep it on my shoulders.",
        "Are you into tricks or treats? Because I can do both.",
        "I’m not an electrician, but I can light up your day.",
        "Do you have a name you want me to save you as in my phone or should I just put 'mine'?",
        "Do you believe in love at first swipe, or should I match with you again?",
        "Are you a piano, Because i wanna use my fingers to play with you until you make beautiful noice.",
        "There are many eggs in the world, but i want to fertilize yours.",
        "I'm like a firefighter i find hot and leave them wet.",
        "Are you cigarette? Because i am have an urge to feel you with my fingers.",
        "Are you Siri? Because you autocomplete me.",
        "Are you a sports bike? Because i wanna ride you faster.",
        "Are you a camera? Because every time I look at you, I smile",
        "Are you an artist? Because you are really good at drawing me in.",
        "Is your name Wi-Fi? Because I'm really feeling a connection.",
        "Can I borrow a map? I keep getting lost in your eyes.", 
        "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
        "Are you a time traveler? Because I can not imagine my future without you.",
        "Do you believe in love at first sight, or should I walk by again?",
        "If you were a cat, you had purr-fect.",
        "Are you a camera? Every time I look at you, I smile.",
        "Excuse me, but I think you dropped something: MY JAW!",
        "Do you have a name, or can I call you mine?",
        "If you were words on a page, you had be fine print.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Excuse me, but I think you dropped something: MY JAW!",
        "Do you have a name, or can I call you mine?",
        "If you were words on a page, you’d be fine print.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "If you were a cat, you had purr-fect.",
        "Do you have a sunburn, or are you always this hot?",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Excuse me, but I think the stars tonight are outshone by your beauty.",
        "If you were a vegetable, you’d be a cute-cumber! ", 
        "Do you have a sunburn, or are you always this hot?",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Excuse me, but I think the stars tonight are outshone by your beauty.",
        "If you were a vegetable, you’d be a cute-cumber!",
        "Can I borrow a map? I keep getting lost in your eyes.",
        "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
        "Are you a time traveler? Because I can’t imagine my future without you.",
        "Do you believe in love at first sight, or should I walk by again?",
        "If you were a cat, you’d purr-fect.",
        "Are you a camera? Every time I look at you, I smile.", 
        "Are you a time traveler? Because I can’t imagine my future without you.",
        "Do you believe in love at first sight, or should I walk by again?",
        "If you were a cat, you’d purr-fect.",
        "Are you a camera? Every time I look at you, I smile.",
        "Excuse me, but I think you dropped something: MY JAW!",
        "Do you have a name, or can I call you mine?",
        "If you were words on a page, you’d be fine print.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "If you were a cat, you’d purr-fect.",
        "Excuse me, but I think the stars tonight are outshone by your beauty.",
        "If you were a vegetable, you’d be a cute-cumber!",
        "Can I borrow a map? I keep getting lost in your eyes.",
        "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
        "Are you a time traveler? Because I can’t imagine my future without you.",
        "Do you believe in love at first sight, or should I walk by again?",
        "If you were a cat, you’d purr-fect.",
        "Are you a camera? Every time I look at you, I smile.",
        "Excuse me, but I think you dropped something: MY JAW!",
        "Do you have a name, or can I call you mine?",
        "If you were words on a page, you’d be fine print.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "If you were a cat, you’d purr-fect.",
        "Do you have a sunburn, or are you always this hot?",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Excuse me, but I think the stars tonight are outshone by your beauty.",
        "If you were a vegetable, you’d be a cute-cumber!",
        "Can I borrow a map? I keep getting lost in your eyes.",
        "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Do you have a map? I keep getting lost in your eyes.",
        "Are you a parking ticket? Because you’ve got Fine written all over you.",
        "If beauty were time, you’d be an eternity.",
        "Can I follow you home? Cause my parents always told me to follow my dreams.",
        "Are you a camera? Every time I look at you, I smile.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "Excuse me, but I think the stars tonight are outshone by your beauty.",
        "If you were a vegetable, you’d be a cute-cumber!",
        "Do you believe in love at first sight, or should I walk by again?",
        "Are you a Wi-Fi signal? Because I’m feeling a connection.",
        "Can I take a picture of you, so I can show Santa exactly what I want for Christmas?",
        "If beauty were time, you’d be an eternity.",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Excuse me, I think you dropped something: MY JAW!",
        "Are you a bank loan? Because you have my interest!",
        "If you were words on a page, you’d be fine print.",
        "Do you have a sunburn, or are you always this hot?",
        "Are you a campfire? Because you’re hot and I want s'more.",
        "Can I borrow a map? I keep getting lost in your eyes.",
        
      
    ];

    var pickupLine = pickupLines[Math.floor(Math.random() * pickupLines.length)];
    document.getElementById("pickup-line").innerText = pickupLine;
}
